site_name: OpenAAS
repo_url: https://github.com/onpprod/OpenAAS
repo_name: OpenAAS

theme:
  name: material
  language: pt-br

#  logo: assets/aas.png
#  favicon: assets/aas.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

