[project]
name = "openaas"
version = "0.1.0"
description = "OpenAAS is a Python project for Asset Administration Shell (AAS) modeling, OPC UA interoperability, and AASX packaging"
authors = [
    {name = "onpprod",email = "otavionpproducoes@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Topic :: Utilities",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.13",
]

[tool.poetry.urls]
"Code" = "https://github.com/onpprod/OpenAAS"
"Bug Tracker" = "https://github.com/onpprod/OpenAAS/issues"


dependencies = [
    "asyncua>=1.1.5",
    "jsonschema>=4.26.0",
    "pydantic>=2.11.0",
    "pymongo>=4.8.0"
]

[project.scripts]
opcuaserver = "opcuaserver.cli:main"
opcualoader = "opcualoader.cli:main"
aasxpackage = "aasxpackage.cli:main"

[tool.poetry]
packages = [
    { include = "aasmodel" },
    { include = "opcuaserver" },
    { include = "opcualoader" },
    { include = "aasxpackage" }
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
